[package]
name = "fin-data-core"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
uuid = { version = "1.8", features = ["v4", "fast-rng"] }
tempfile = "3.10"
